{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "open-k0rdent-ui.fullname" . }}
  labels:
    {{- include "open-k0rdent-ui.labels" . | nindent 4 }}
rules:
# Core Kubernetes resources
- apiGroups: [""]
  resources: ["namespaces", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
# Authorization API for namespace access checking
- apiGroups: ["authorization.k8s.io"]
  resources: ["selfsubjectaccessreviews"]
  verbs: ["create"]
# Authentication API for user info
- apiGroups: ["authentication.k8s.io"]
  resources: ["selfsubjectreviews"]
  verbs: ["create"]
# k0rdent resources
- apiGroups: ["k0rdent.mirantis.com"]
  resources: ["clusterdeployments", "clustertemplates", "clustertemplatechains", "servicetemplates", "servicetemplatechains", "multiclusterservices", "credentials", "managements", "managementbackups", "providertemplates", "releases", "accessmanagements"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Flux CD HelmRepository resources (for repository management)
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["helmrepositories"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Flux CD GitRepository resources (for Git repository management)
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["gitrepositories"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Flux CD HelmChart resources (for reading chart information)
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmcharts"]
  verbs: ["get", "list", "watch"]
{{- with .Values.rbac.clusterRole.customRules }}
{{- toYaml . | nindent 0 }}
{{- end }}
---
# Add a specific role binding for kcm-system secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "open-k0rdent-ui.fullname" . }}-kcm-system-secrets
  namespace: kcm-system
  labels:
    {{- include "open-k0rdent-ui.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "open-k0rdent-ui.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: {{ include "open-k0rdent-ui.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "open-k0rdent-ui.fullname" . }}
  labels:
    {{- include "open-k0rdent-ui.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "open-k0rdent-ui.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: {{ include "open-k0rdent-ui.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }} 