apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-k0rdent-ui.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "open-k0rdent-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "open-k0rdent-ui.selectorLabels" . | nindent 4 }} 