{{- $global := .Values.global | default dict }}
{{- $version := .Chart.AppVersion }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: aws
spec:
  version: {{ $version }}
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  manager: {{ include "spec.manager" . | nindent 4 }}
  {{- if $global.registry }}
  fetchConfig:
    oci: {{ $global.registry }}/capi/cluster-api-provider-aws-components:{{ $version }}
  {{- end }}
  deployment:
    containers:
      - name: manager
        {{- if $global.registry }}
        imageUrl: {{ $global.registry }}/capi/cluster-api-aws-controller:{{ $version }}
        {{- end }}
        {{- with .Values.managerEnv }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
